# Generated by Django 4.2.2 on 2023-06-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='apellido',
            new_name='pais',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='email',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.PositiveIntegerField(),
        ),
    ]
